// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGCzpyo_KJoss3DhdR1j6m-lpgrmhPDjg',
    appId: '1:1085201917932:web:f0a5a3a9cc8e54748382c9',
    messagingSenderId: '1085201917932',
    projectId: 'foodpanda-clone-app-13715',
    authDomain: 'foodpanda-clone-app-13715.firebaseapp.com',
    storageBucket: 'foodpanda-clone-app-13715.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfLXGoOifUfBWn8qwsIgv6M_8XXtokzQg',
    appId: '1:1085201917932:android:e90199548532cbe08382c9',
    messagingSenderId: '1085201917932',
    projectId: 'foodpanda-clone-app-13715',
    storageBucket: 'foodpanda-clone-app-13715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCKDflQLs3Rym7v7h7vijVRIEKSq4Gis',
    appId: '1:1085201917932:ios:d2ab66bfa9a01d748382c9',
    messagingSenderId: '1085201917932',
    projectId: 'foodpanda-clone-app-13715',
    storageBucket: 'foodpanda-clone-app-13715.appspot.com',
    androidClientId: '1085201917932-iiite0sho82c751ukd3g1pj0aqvhlf29.apps.googleusercontent.com',
    iosClientId: '1085201917932-thf8hfr5d04fkh41r53ra56s01revogi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifoodUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBCKDflQLs3Rym7v7h7vijVRIEKSq4Gis',
    appId: '1:1085201917932:ios:d2ab66bfa9a01d748382c9',
    messagingSenderId: '1085201917932',
    projectId: 'foodpanda-clone-app-13715',
    storageBucket: 'foodpanda-clone-app-13715.appspot.com',
    androidClientId: '1085201917932-iiite0sho82c751ukd3g1pj0aqvhlf29.apps.googleusercontent.com',
    iosClientId: '1085201917932-thf8hfr5d04fkh41r53ra56s01revogi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifoodUserApp',
  );
}
